### ISSUE TITLE
copyItem does not prepare opts.mkdirpAsync

### ISSUE THREAD

**Issue by tigersoldier** [npm/copy-concurrently#1]
I got this error using npm install (npm 5.2.0):

> 12218 verbose stack TypeError: opts.mkdirpAsync is not a function
> 12218 verbose stack     at recurseDir (/usr/local/google/home/chencaibin/.npm-packages/lib/node_modules/npm/node_modules/move-concurrently/node_modules/copy-concurrently/copy.js:130:15)
> 12218 verbose stack     at /usr/local/google/home/chencaibin/.npm-packages/lib/node_modules/npm/node_modules/move-concurrently/node_modules/copy-concurrently/copy.js:104:14
> 12218 verbose stack     at tryCatcher (/usr/local/google/home/chencaibin/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
> 12218 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/google/home/chencaibin/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
> 12218 verbose stack     at Promise._settlePromise (/usr/local/google/home/chencaibin/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
> 12218 verbose stack     at Promise._settlePromise0 (/usr/local/google/home/chencaibin/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
> 12218 verbose stack     at Promise._settlePromises (/usr/local/google/home/chencaibin/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
> 12218 verbose stack     at Async._drainQueue (/usr/local/google/home/chencaibin/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
> 12218 verbose stack     at Async._drainQueues (/usr/local/google/home/chencaibin/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
> 12218 verbose stack     at Immediate.Async.drainQueues (/usr/local/google/home/chencaibin/.npm-packages/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
> 12218 verbose stack     at runCallback (timers.js:800:20)
> 12218 verbose stack     at tryOnImmediate (timers.js:762:5)
> 12218 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
> 12219 verbose cwd /google/src/cloud/chencaibin/cce-samples-package-3691/google3/experimental/users/chencaibin/cce-samples/nodejs/samples
> 

By reading the code, copy() prepares opts.mkdirpAsync:
`  opts.mkdirpAsync = promisify(opts.Promise, mkdirp)
`

However, if copyItem() is called directly without copy(), opts.mkdirpAsync is undefined.

**Comment by huan** [comment]
+1

**Comment by iarna** [comment]
Fixed in 1.0.4

**Comment by hallmark** [comment]
@iarna Any idea whether `npm` will be updating its `package-lock.json` to pull in `copy-concurrently@1.0.4`?

This would be a fantastic fix to have in the next release of `npm` - and then hopefully included by default in Node soon.

**Comment by iarna** [comment]
Oh shoot, thanks for the poke! I'll make sure this gets into the next release!

**Comment by iarna** [comment]
I've done this over in npm's `release-next` branch as https://github.com/npm/npm/commit/d0da195f3c6319a80aeddbdb9585a28b9959ceee
